convert -resize 20x20! abeja.0cb61e35.0cb61e35.gif convabeja.0cb61e35.0cb61e35.gif 
convert -resize 20x20! abeja.0cb61e35.gif abeja.0cb61e35.gif 
convert -resize 20x20! abeja.gif abeja.gif 
convert -resize 20x20! AceleracionAmarilla.png AceleracionAmarilla.png 
convert -resize 20x20! AceleracionAzul.png AceleracionAzul.png 
convert -resize 20x20! AceleracionRoja.png AceleracionRoja.png 
convert -resize 20x20! actualizacionfinalizada.png actualizacionfinalizada.png 
convert -resize 20x20! actualizacioniniciada.png actualizacioniniciada.png 
convert -resize 20x20! alertas.08ce3697.jpg alertas.08ce3697.jpg 
convert -resize 20x20! AsistenteManejoDefensivo.png AsistenteManejoDefensivo.png 
convert -resize 20x20! attentionBlue.png attentionBlue.png 
convert -resize 20x20! attentionOrange.png attentionOrange.png 
convert -resize 20x20! attentionPurple.png attentionPurple.png 
convert -resize 20x20! attentionRed.png attentionRed.png 
convert -resize 20x20! BateriaConectada.png BateriaConectada.png 
convert -resize 20x20! BateriaDesconectada.png BateriaDesconectada.png 
convert -resize 20x20! bateria-eco-OFF.svg bateria-eco-OFF.svg 
convert -resize 20x20! bateria-eco-ON.svg bateria-eco-ON.svg 
convert -resize 20x20! businessman.png businessman.png 
convert -resize 20x20! car.62ba816e.png car.62ba816e.png 
convert -resize 20x20! car.d41d8cd9.png car.d41d8cd9.png 
convert -resize 20x20! car.png car.png 
convert -resize 20x20! cars.3a0b84ab.png cars.3a0b84ab.png 
convert -resize 20x20! cars.png cars.png 
convert -resize 20x20! championX.jpg championX.jpg 
convert -resize 20x20! coche-electrico-OFF.png coche-electrico-OFF.png 
convert -resize 20x20! coche-electrico-ON.png coche-electrico-ON.png 
convert -resize 20x20! copia-de-seguridad.png copia-de-seguridad.png 
convert -resize 20x20! copia-de-seguridad.svg copia-de-seguridad.svg 
convert -resize 20x20! createRoute.b50bc953.png createRoute.b50bc953.png 
convert -resize 20x20! createRoute.png createRoute.png 
convert -resize 20x20! credit-card.png credit-card.png 
convert -resize 20x20! cursor.png cursor.png 
convert -resize 20x20! cursor.svg cursor.svg 
convert -resize 20x20! delete.06f5cb41.png delete.06f5cb41.png 
convert -resize 20x20! delete.d41d8cd9.png delete.d41d8cd9.png 
convert -resize 20x20! dormir1.png dormir1.png 
convert -resize 20x20! dormir2.png dormir2.png 
convert -resize 20x20! dormir.png dormir.png 
convert -resize 20x20! eco-coche-OFF.svg eco-coche-OFF.svg 
convert -resize 20x20! eco-coche-ON.svg eco-coche-ON.svg 
convert -resize 20x20! eco-enchufe-OFF.png eco-enchufe-OFF.png 
convert -resize 20x20! eco-enchufe-OFF.svg eco-enchufe-OFF.svg 
convert -resize 20x20! eco-enchufe-on.png eco-enchufe-on.png 
convert -resize 20x20! eco-enchufe-ON.svg eco-enchufe-ON.svg 
convert -resize 20x20! eco-energiaOFF.png eco-energiaOFF.png 
convert -resize 20x20! eco-energia-OFF.svg eco-energia-OFF.svg 
convert -resize 20x20! eco-energia-ON.png eco-energia-ON.png 
convert -resize 20x20! eco-energia-ON.svg eco-energia-ON.svg 
convert -resize 20x20! ECOLAB3.jpg ECOLAB3.jpg 
convert -resize 20x20! ecolab-full.png ecolab-full.png 
convert -resize 20x20! ecooff.png ecooff.png 
convert -resize 20x20! ecoon1.png ecoon1.png 
convert -resize 20x20! ecoon.png ecoon.png 
convert -resize 20x20! energia-eco-poder-OFF.png energia-eco-poder-OFF.png 
convert -resize 20x20! energia-eco-poder-OFF.svg energia-eco-poder-OFF.svg 
convert -resize 20x20! energia-eco-poder-ON.png energia-eco-poder-ON.png 
convert -resize 20x20! energia-eco-poder-ON.svg energia-eco-poder-ON.svg 
convert -resize 20x20! estrella.png estrella.png 
convert -resize 20x20! ExternalBatteryLow.png ExternalBatteryLow.png 
convert -resize 20x20! flash.png flash.png 
convert -resize 20x20! Flecah_EX.png Flecah_EX.png 
convert -resize 20x20! flechaazul.png flechaazul.png 
convert -resize 20x20! flecha-hacia-arriba-de-raton.png flecha-hacia-arriba-de-raton.png 
convert -resize 20x20! flecha-hacia-arriba-de-raton.svg flecha-hacia-arriba-de-raton.svg 
convert -resize 20x20! flecharoja.png flecharoja.png 
convert -resize 20x20! flechaverde(Custom).png flechaverde(Custom).png 
convert -resize 20x20! flechaverde.png flechaverde.png 
convert -resize 20x20! flechaverde.svg flechaverde.svg 
convert -resize 20x20! FrenadaAmarilla2.png FrenadaAmarilla2.png 
convert -resize 20x20! FrenadaAmarilla.png FrenadaAmarilla.png 
convert -resize 20x20! FrenadaAzul2.png FrenadaAzul2.png 
convert -resize 20x20! FrenadaAzul.png FrenadaAzul.png 
convert -resize 20x20! FrenadaRoja2.png FrenadaRoja2.png 
convert -resize 20x20! FrenadaRoja.png FrenadaRoja.png 
convert -resize 20x20! fullcontrol2.png fullcontrol2.png 
convert -resize 20x20! fullcontrol.png fullcontrol.png 
convert -resize 20x20! green.jpg green.jpg 
convert -resize 20x20! green.png green.png 
convert -resize 20x20! gris.png gris.png 
convert -resize 20x20! gsm.png gsm.png 
convert -resize 20x20! hombre-derribado.png hombre-derribado.png 
convert -resize 20x20! HorarioNocturnoNegro.png HorarioNocturnoNegro.png 
convert -resize 20x20! HorarioNocturnoRojo.png HorarioNocturnoRojo.png 
convert -resize 20x20! humedadOFF.png humedadOFF.png 
convert -resize 20x20! humedadON.png humedadON.png 
convert -resize 20x20! icon.png icon.png 
convert -resize 20x20! IdentificacionAzul.png IdentificacionAzul.png 
convert -resize 20x20! IdentificacionGris.png IdentificacionGris.png 
convert -resize 20x20! IdentificacionRoja.png IdentificacionRoja.png 
convert -resize 20x20! IdentificacionVerde.png IdentificacionVerde.png 
convert -resize 20x20! ignicionoff.png ignicionoff.png 
convert -resize 20x20! ignicionon.png ignicionon.png 
convert -resize 20x20! imagesimages
convert -resize 20x20! impresora(1).png impresora(1).png 
convert -resize 20x20! impresora(1).svg impresora(1).svg 
convert -resize 20x20! impresora(2).png impresora(2).png 
convert -resize 20x20! impresora(2).svg impresora(2).svg 
convert -resize 20x20! impresora(3).png impresora(3).png 
convert -resize 20x20! impresora.png impresora.png 
convert -resize 20x20! impresora.svg impresora.svg 
convert -resize 20x20! InternalBatteryLow.png InternalBatteryLow.png 
convert -resize 20x20! load.gif load.gif 
convert -resize 20x20! logo-de-pago-eco-OFF.svg logo-de-pago-eco-OFF.svg 
convert -resize 20x20! logo-de-pago-eco-ON.svg logo-de-pago-eco-ON.svg 
convert -resize 20x20! logofull.png logofull.png 
convert -resize 20x20! logo.png logo.png 
convert -resize 20x20! LunaAmarilla1.png LunaAmarilla1.png 
convert -resize 20x20! LunaAmarilla2.png LunaAmarilla2.png 
convert -resize 20x20! LunaBlanca.png LunaBlanca.png 
convert -resize 20x20! LunaNegra.png LunaNegra.png 
convert -resize 20x20! mapa.e3870e84.svg mapa.e3870e84.svg 
convert -resize 20x20! mapa.svg mapa.svg 
convert -resize 20x20! maxima100verde.png maxima100verde.png 
convert -resize 20x20! maxima110verde.png maxima110verde.png 
convert -resize 20x20! maxima120verde.png maxima120verde.png 
convert -resize 20x20! maxima130verde.png maxima130verde.png 
convert -resize 20x20! maxima20verde.png maxima20verde.png 
convert -resize 20x20! maxima40verde.png maxima40verde.png 
convert -resize 20x20! maxima50verde.png maxima50verde.png 
convert -resize 20x20! maxima60verde.png maxima60verde.png 
convert -resize 20x20! maxima80verde.png maxima80verde.png 
convert -resize 20x20! maxima90verde.png maxima90verde.png 
convert -resize 20x20! MultaAzul.png MultaAzul.png 
convert -resize 20x20! noche.png noche.png 
convert -resize 20x20! pedestrian.png pedestrian.png 
convert -resize 20x20! pie-chart.png pie-chart.png 
convert -resize 20x20! pink.png pink.png 
convert -resize 20x20! plus.png plus.png 
convert -resize 20x20! publicTransport.png publicTransport.png 
convert -resize 20x20! RalentiEnd.png RalentiEnd.png 
convert -resize 20x20! RalentiStart.png RalentiStart.png 
convert -resize 20x20! rayo-energia-electrica.png rayo-energia-electrica.png 
convert -resize 20x20! rayo-luminoso-sombra.png rayo-luminoso-sombra.png 
convert -resize 20x20! rayo.png rayo.png 
convert -resize 20x20! reloj.a4b04d7d.svg reloj.a4b04d7d.svg 
convert -resize 20x20! reloj.svg reloj.svg 
convert -resize 20x20! reportedetenidochico.png reportedetenidochico.png 
convert -resize 20x20! rgb.png rgb.png 
convert -resize 20x20! rgb.svg rgb.svg 
convert -resize 20x20! ruta.jpg ruta.jpg 
convert -resize 20x20! signoPregunta.png signoPregunta.png 
convert -resize 20x20! sueno.png sueno.png 
convert -resize 20x20! transparente.png transparente.png 
convert -resize 20x20! Under-the-green-arrow-1128044251.png Under-the-green-arrow-1128044251.png 
convert -resize 20x20! unidad-de-energia-eco-OFF.svg unidad-de-energia-eco-OFF.svg 
convert -resize 20x20! unidad-de-energia-eco-ON.svg unidad-de-energia-eco-ON.svg 
convert -resize 20x20! up.png up.png 
convert -resize 20x20! verde.png verde.png 
convert -resize 20x20! virnetconectado.png virnetconectado.png 
convert -resize 20x20! virnetdesconectado.png virnetdesconectado.png 
convert -resize 20x20! VuelcoAmarillo.png VuelcoAmarillo.png 
convert -resize 20x20! VuelcoAzul.png VuelcoAzul.png 
convert -resize 20x20! VuelcoRojo.png VuelcoRojo.png 